<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_prev_page</name>
   <tag></tag>
   <elementGuidId>c286c9fc-c501-4068-be40-4cc846b867ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Trước')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.join-item.btn.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f8ced83a-3538-4ac7-a491-0ec243769ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>join-item btn btn-sm </value>
      <webElementGuid>255cd11f-dba2-4216-bfbe-cb2dedee3b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>12836e2c-d618-47f6-ba4d-919bbe725696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/?page=1</value>
      <webElementGuid>5d3aa140-ee69-4167-8304-d0ddecaefc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Trước</value>
      <webElementGuid>841e9bbc-9ef9-443b-8a9e-5504b6c50ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;geist_a71539c9-module__T19VSG__variable geist_mono_8d43a2aa-module__8Li5zG__variable antialiased&quot;]/div[@class=&quot;drawer&quot;]/div[@class=&quot;drawer-content&quot;]/main[@class=&quot;container mx-auto p-4 md:p-6 lg:p-8&quot;]/div[@class=&quot;space-y-6&quot;]/div[@class=&quot;flex justify-center&quot;]/div[@class=&quot;join&quot;]/a[@class=&quot;join-item btn btn-sm&quot;]</value>
      <webElementGuid>24691c92-e6b8-4930-8b95-155e546235a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Trước')]</value>
      <webElementGuid>cbf79393-2bba-41a4-b64f-05d5392898db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xem chi tiết'])[4]/following::a[1]</value>
      <webElementGuid>bd45baa3-0bf3-4d39-9d35-3e675804c6ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VolunteerHub'])[2]/preceding::a[4]</value>
      <webElementGuid>9a5f53b9-046a-4234-8d6c-0833045b10d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang chủ'])[1]/preceding::a[4]</value>
      <webElementGuid>51ac8939-6966-4f08-8b36-78217e00ae9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Trước']/parent::*</value>
      <webElementGuid>0b33687c-123d-4264-ab03-f70e2b246a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/?page=1')]</value>
      <webElementGuid>a796720f-7a22-4a6d-ba5f-9c47c1576a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a</value>
      <webElementGuid>8f351604-ad43-408e-807b-e5e90aca4143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/?page=1' and (text() = 'Trước' or . = 'Trước')]</value>
      <webElementGuid>bb486782-9780-4a18-8e9c-1adcccfe2809</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
