<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>danhmuc_drop</name>
   <tag></tag>
   <elementGuidId>66ffa6e4-37d7-4c1e-8eaf-2010f0594a04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#category</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='category']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3d42ac3d-93e5-4ee2-b943-11ba64444420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>4c7f70a3-cf5f-45c4-b6ca-a38aa4a5a373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>b07af064-a2e3-4a77-bcb1-376d4d7b530e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select select-bordered w-full pl-3</value>
      <webElementGuid>f79ad478-c3aa-466e-b825-2ded02196548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tất cả danh mục🌱 Môi trường📚 Giáo dục⚕️ Y tế - Sức khỏe🤝 Cộng đồng</value>
      <webElementGuid>d09a501b-c8ff-4251-956f-432ea7283fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category&quot;)</value>
      <webElementGuid>bf18bd02-9bd9-4e40-b462-11a66fb72f02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='category']</value>
      <webElementGuid>fe5cbb26-a004-4ab9-aea7-e23de63c6253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh mục'])[1]/following::select[1]</value>
      <webElementGuid>9023842a-66a8-4513-8e85-69af1c972889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sự kiện sắp tới'])[1]/following::select[1]</value>
      <webElementGuid>0095ddaa-7b6b-49b9-abc0-1e10661cab32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sắp xếp theo'])[1]/preceding::select[1]</value>
      <webElementGuid>9c0104f5-1d03-4ccd-ac75-f568a5deea49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🌱'])[1]/preceding::select[2]</value>
      <webElementGuid>f0172c5f-0365-4c67-91ba-f299c31e1aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>cd6957e3-28c1-4fa4-a6f4-3f58eda341d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'category' and @name = 'category' and (text() = 'Tất cả danh mục🌱 Môi trường📚 Giáo dục⚕️ Y tế - Sức khỏe🤝 Cộng đồng' or . = 'Tất cả danh mục🌱 Môi trường📚 Giáo dục⚕️ Y tế - Sức khỏe🤝 Cộng đồng')]</value>
      <webElementGuid>61814728-6e0d-4d63-9725-dd85363ffd96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
