<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>danhmuc_dropdown</name>
   <tag></tag>
   <elementGuidId>dce0fb3d-9a9a-43fc-bb5d-62fed1480227</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='category']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#category</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b064a433-bb54-43eb-8bf8-fd48b30c5a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>2f252d4a-7774-4916-a4bf-ced49b30375f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>8ec066b5-4b13-4804-bfd4-bdad656af7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select select-bordered w-full pl-3</value>
      <webElementGuid>eba6744c-a278-42ac-81c7-ce97a7dd7449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tất cả danh mục🌱 Môi trường📚 Giáo dục⚕️ Y tế - Sức khỏe🤝 Cộng đồng</value>
      <webElementGuid>af47824b-b614-41cf-a37a-1622cef50574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category&quot;)</value>
      <webElementGuid>1511f68c-de5a-43b8-be2a-b40910254aa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='category']</value>
      <webElementGuid>c668bac0-4358-4d94-9828-89c5d723186a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh mục'])[1]/following::select[1]</value>
      <webElementGuid>fbe9e676-b709-4657-83c0-973aaa8a1a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sự kiện sắp tới'])[1]/following::select[1]</value>
      <webElementGuid>1474698c-f50c-4d72-ab36-9b9ff4f5d3f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sắp xếp theo'])[1]/preceding::select[1]</value>
      <webElementGuid>4e5908d3-584e-4b02-aef4-7c632a6c6611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='📚'])[1]/preceding::select[2]</value>
      <webElementGuid>7f279d3e-6790-4740-987e-b3fa02254214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>08700824-aa8b-4692-b1cc-1a18fa9faa95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'category' and @name = 'category' and (text() = 'Tất cả danh mục🌱 Môi trường📚 Giáo dục⚕️ Y tế - Sức khỏe🤝 Cộng đồng' or . = 'Tất cả danh mục🌱 Môi trường📚 Giáo dục⚕️ Y tế - Sức khỏe🤝 Cộng đồng')]</value>
      <webElementGuid>5592b33a-ecfe-47be-966a-8bc7bb11b64b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
