<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>skddki</name>
   <tag></tag>
   <elementGuidId>a262ad5f-0836-4982-ad9f-a0d777dd76f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Làm sạch kênh mương – Chung tay vì nước sạch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.object-cover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fd29a18a-e00e-4b4b-a1a1-f405aa6f1045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Làm sạch kênh mương – Chung tay vì nước sạch</value>
      <webElementGuid>6a0ea456-6f88-48b6-8448-6790a0bf69fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>b47add8b-f47b-4c13-ba38-021aa67eacc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>daaf3c09-883d-4dce-b446-686a81dc9458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>6c4becb3-3c81-4a66-8eb4-c8a44638bbc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>object-cover</value>
      <webElementGuid>88359406-7f87-4836-9ec4-74f2ed997a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/uploads/events/1765151136969-p4xlm1.jpg</value>
      <webElementGuid>6eb0880a-f7ee-4c3d-94f0-79b80ba09125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;geist_a71539c9-module__T19VSG__variable geist_mono_8d43a2aa-module__8Li5zG__variable antialiased&quot;]/div[@class=&quot;drawer&quot;]/div[@class=&quot;drawer-content&quot;]/main[@class=&quot;container mx-auto p-4 md:p-6 lg:p-8&quot;]/div[@class=&quot;max-w-6xl mx-auto p-4 md:p-8&quot;]/div[@class=&quot;space-y-12&quot;]/section[1]/div[@class=&quot;grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8&quot;]/a[@class=&quot;group&quot;]/div[@class=&quot;card bg-base-100 shadow-lg hover:shadow-2xl transition-all duration-300 border border-base-300 h-full group-hover:-translate-y-1&quot;]/figure[@class=&quot;relative h-48 bg-gradient-to-br from-primary/20 to-secondary/20&quot;]/img[@class=&quot;object-cover&quot;]</value>
      <webElementGuid>e87a6225-bc46-49a7-a1c4-5f2fe15e2f3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Làm sạch kênh mương – Chung tay vì nước sạch']</value>
      <webElementGuid>88037dd0-9524-4d12-b3c1-8aa00afc9048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>f2fbec70-fdfb-42df-8415-2769e5fcc30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Làm sạch kênh mương – Chung tay vì nước sạch' and @src = '/uploads/events/1765151136969-p4xlm1.jpg']</value>
      <webElementGuid>355974f8-ea9e-4333-be99-de18d2a95593</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
