<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>skienn</name>
   <tag></tag>
   <elementGuidId>9c2b0a98-f47b-413e-8727-97da92873da4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Làm sạch kênh mương – Chung tay vì nước sạch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.object-cover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1853d2aa-0f40-42ee-ab9e-6551eea40fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Làm sạch kênh mương – Chung tay vì nước sạch</value>
      <webElementGuid>fdf0a714-a746-4564-a281-ca0abc01c6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>33c627b6-7de9-46c9-83cd-571c72fc1392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>37964350-09ae-4481-8cad-5470c20067c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>513888ed-7f21-4fda-bab8-c3e015bc1205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>object-cover</value>
      <webElementGuid>a26becb0-a84e-4bb4-9ac6-69b7dff9317a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/uploads/events/1765151136969-p4xlm1.jpg</value>
      <webElementGuid>4af462f3-2b84-44a6-baf5-ee8e9279503c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;geist_a71539c9-module__T19VSG__variable geist_mono_8d43a2aa-module__8Li5zG__variable antialiased&quot;]/div[@class=&quot;drawer&quot;]/div[@class=&quot;drawer-content&quot;]/main[@class=&quot;container mx-auto p-4 md:p-6 lg:p-8&quot;]/div[@class=&quot;space-y-6&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6&quot;]/a[@class=&quot;group&quot;]/div[@class=&quot;card bg-base-100 shadow-lg hover:shadow-2xl transition-all duration-300 border border-base-300 h-full group-hover:-translate-y-1&quot;]/figure[@class=&quot;relative h-48 bg-gradient-to-br from-primary/20 to-secondary/20&quot;]/img[@class=&quot;object-cover&quot;]</value>
      <webElementGuid>5d59be6d-62b3-4954-84c9-579e282b7ca4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Làm sạch kênh mương – Chung tay vì nước sạch']</value>
      <webElementGuid>24f55fc7-0b55-476b-b171-58e18fe6aa69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>5fcfbdc2-c83b-4d5b-ad3f-1b1cae6759a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Làm sạch kênh mương – Chung tay vì nước sạch' and @src = '/uploads/events/1765151136969-p4xlm1.jpg']</value>
      <webElementGuid>8cfe6bd4-d53b-4915-9824-4928d371e9f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
