<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>skiendadki_link</name>
   <tag></tag>
   <elementGuidId>ba62e248-fc6c-4608-b011-353c1719ac9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.object-cover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Trồng cây gây rừng nhỏ – Vì một Ba Vì xanh']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b7b0c55f-d73a-4dd0-9190-fe5134c21c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Trồng cây gây rừng nhỏ – Vì một Ba Vì xanh</value>
      <webElementGuid>96c36aa3-9eb2-45b7-8c9a-e94cd246b746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>0d5dd686-4d32-4c60-a63a-ea0f8faad419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>9316196e-0742-40c2-8f33-fac874f374fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>8174228e-7880-42b7-8c99-b3052f22eaeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>object-cover</value>
      <webElementGuid>f6fdc2df-b56c-4ea8-8a69-ce8d225b6e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/uploads/events/1765151263588-n32u01.jpg</value>
      <webElementGuid>92048bfd-fa3c-4961-8809-2838e89c0439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;geist_a71539c9-module__T19VSG__variable geist_mono_8d43a2aa-module__8Li5zG__variable antialiased&quot;]/div[@class=&quot;drawer&quot;]/div[@class=&quot;drawer-content&quot;]/main[@class=&quot;container mx-auto p-4 md:p-6 lg:p-8&quot;]/div[@class=&quot;max-w-6xl mx-auto p-4 md:p-8&quot;]/div[@class=&quot;space-y-12&quot;]/section[1]/div[@class=&quot;grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8&quot;]/a[@class=&quot;group&quot;]/div[@class=&quot;card bg-base-100 shadow-lg hover:shadow-2xl transition-all duration-300 border border-base-300 h-full group-hover:-translate-y-1&quot;]/figure[@class=&quot;relative h-48 bg-gradient-to-br from-primary/20 to-secondary/20&quot;]/img[@class=&quot;object-cover&quot;]</value>
      <webElementGuid>de939ba4-a444-49bc-9472-7bde8853a4b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Trồng cây gây rừng nhỏ – Vì một Ba Vì xanh']</value>
      <webElementGuid>956de5ff-531a-4b9c-831e-cd7317fe2cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>8bb0caad-9cc0-426c-bb9b-96653ef7ab37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Trồng cây gây rừng nhỏ – Vì một Ba Vì xanh' and @src = '/uploads/events/1765151263588-n32u01.jpg']</value>
      <webElementGuid>19d4f717-e5d3-4d3b-b730-f1014df40bcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
