<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>skien1</name>
   <tag></tag>
   <elementGuidId>7ae3e61a-48ac-4243-8c1e-5aad4eeaa1f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.object-cover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Trồng cây gây rừng nhỏ – Vì một Ba Vì xanh']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>88bc2ca3-5fdd-4559-861f-76fd081c9d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Trồng cây gây rừng nhỏ – Vì một Ba Vì xanh</value>
      <webElementGuid>0202c7c6-4b3f-4a3c-9f7d-b9f5daad60f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>ee00df1f-53a7-4a13-a34c-dc75598ec59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>578c4c30-6548-4b25-94f8-0b60e302216a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>eb55b0a5-e514-4d28-8057-c0413efc5994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>object-cover</value>
      <webElementGuid>1c656be8-a1a1-4857-9590-bb93edd6afda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/uploads/events/1765151263588-n32u01.jpg</value>
      <webElementGuid>dd7609cd-36f8-4443-813f-b181740f5a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;geist_a71539c9-module__T19VSG__variable geist_mono_8d43a2aa-module__8Li5zG__variable antialiased&quot;]/div[@class=&quot;drawer&quot;]/div[@class=&quot;drawer-content&quot;]/main[@class=&quot;container mx-auto p-4 md:p-6 lg:p-8&quot;]/div[@class=&quot;space-y-6&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6&quot;]/a[@class=&quot;group&quot;]/div[@class=&quot;card bg-base-100 shadow-lg hover:shadow-2xl transition-all duration-300 border border-base-300 h-full group-hover:-translate-y-1&quot;]/figure[@class=&quot;relative h-48 bg-gradient-to-br from-primary/20 to-secondary/20&quot;]/img[@class=&quot;object-cover&quot;]</value>
      <webElementGuid>20928df0-90eb-4e90-83f1-0bdc80a9b670</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Trồng cây gây rừng nhỏ – Vì một Ba Vì xanh']</value>
      <webElementGuid>1c03b4e5-16c5-4ebd-b00a-789aace08aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>7c2b9146-dcdb-4636-b2ab-18e72e24c593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Trồng cây gây rừng nhỏ – Vì một Ba Vì xanh' and @src = '/uploads/events/1765151263588-n32u01.jpg']</value>
      <webElementGuid>70ef3ac8-0bd4-43ff-9555-618f99e3759e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
