<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sort_dropdown</name>
   <tag></tag>
   <elementGuidId>7f888d9b-9f6e-4b77-a944-ba2bc5835822</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sortBy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sortBy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6f566d24-df3c-42e3-9712-d6a602a9ca1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sortBy</value>
      <webElementGuid>984a5a6e-67d5-4dc1-93aa-2d6c1b87b26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sortBy</value>
      <webElementGuid>486041c9-e390-4e5a-9e06-cfc9805a48dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select select-bordered w-full pl-3</value>
      <webElementGuid>ee706d51-087a-448b-a5c2-d3772879d718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>📅 Ngày bắt đầu🔤 Tên (A-Z)</value>
      <webElementGuid>60e410ea-f8e0-4c88-ab4c-422ffb4ff6d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sortBy&quot;)</value>
      <webElementGuid>ee958b59-975b-41a2-94ab-dce84454d0ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='sortBy']</value>
      <webElementGuid>a332b9e1-ae8e-4e61-9dce-71b34dfa4785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sắp xếp theo'])[1]/following::select[1]</value>
      <webElementGuid>c03f5bd2-5e40-451a-8eda-0238b9d50540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh mục'])[1]/following::select[2]</value>
      <webElementGuid>bd11f237-70a3-4bc2-9885-02c22e46083e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='📚'])[1]/preceding::select[1]</value>
      <webElementGuid>ca1944dd-e167-4ffa-abf3-11a52af809ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N'])[1]/preceding::select[1]</value>
      <webElementGuid>95dcb226-8438-4047-83cb-59194a8d7bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>bdebff86-5bf2-4071-b562-a047a798274d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'sortBy' and @name = 'sortBy' and (text() = '📅 Ngày bắt đầu🔤 Tên (A-Z)' or . = '📅 Ngày bắt đầu🔤 Tên (A-Z)')]</value>
      <webElementGuid>92710e6e-8e03-4bfb-b11e-0ab2fc94b60d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
