<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sort_by</name>
   <tag></tag>
   <elementGuidId>13c969c5-a4e1-4e98-9372-a269122e8802</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sortBy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sortBy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>27c4aaf1-3e5d-46b6-b50f-0abc4d7d2466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sortBy</value>
      <webElementGuid>fb79aac6-fad9-491c-9724-c2f3392a52fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sortBy</value>
      <webElementGuid>c4a71f67-8b2f-4bcf-a85f-8ee93e88fc44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select select-bordered w-full pl-3</value>
      <webElementGuid>575db109-8b96-4128-b8a0-2549f2e64832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>📅 Ngày bắt đầu🔤 Tên (A-Z)</value>
      <webElementGuid>d524bbce-c015-4ea6-9324-ef75a6dc6f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sortBy&quot;)</value>
      <webElementGuid>a5bce018-b0de-4fe2-81ea-62f138fab644</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='sortBy']</value>
      <webElementGuid>da92cd43-94cb-4f0e-9805-c75ac23b0468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sắp xếp theo'])[1]/following::select[1]</value>
      <webElementGuid>62cbc4ca-f5c4-4dee-bac4-a3649dfb1ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh mục'])[1]/following::select[2]</value>
      <webElementGuid>5728d90f-bc35-4512-a945-96e36598b721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🌱'])[1]/preceding::select[1]</value>
      <webElementGuid>be587d24-03c9-4221-b587-a66c5f454a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='atunx'])[1]/preceding::select[1]</value>
      <webElementGuid>fee394e5-0acb-451e-ad21-c049a860407c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>b747ef6b-1461-4ee6-bd51-e2391e5572ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'sortBy' and @name = 'sortBy' and (text() = '📅 Ngày bắt đầu🔤 Tên (A-Z)' or . = '📅 Ngày bắt đầu🔤 Tên (A-Z)')]</value>
      <webElementGuid>39830799-c5dd-4c36-99c3-bc58e78f1f23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
